version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_local
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Str0ng!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Str0ng!Passw0rd",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  mssql_data:
